-- Aggiorna tabella persone: aggiungi colonne ruolo e colore se mancanti
ALTER TABLE persone ADD COLUMN IF NOT EXISTS ruolo   TEXT;
ALTER TABLE persone ADD COLUMN IF NOT EXISTS colore  TEXT DEFAULT '#3d7fff';

-- Tabella categorie personalizzabili
CREATE TABLE IF NOT EXISTS categorie (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome       TEXT NOT NULL,
  emoji      TEXT DEFAULT '📋',
  ctx        TEXT NOT NULL DEFAULT 'lavoro',
  ordine     INT  DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Abilita RLS e policy pubblica (stesso pattern di cicli/persone)
ALTER TABLE categorie ENABLE ROW LEVEL SECURITY;
CREATE POLICY IF NOT EXISTS "Public access" ON categorie FOR ALL USING (true) WITH CHECK (true);
ALTER TABLE persone    ENABLE ROW LEVEL SECURITY;
CREATE POLICY IF NOT EXISTS "Public access" ON persone    FOR ALL USING (true) WITH CHECK (true);

-- Abilita realtime
ALTER PUBLICATION supabase_realtime ADD TABLE categorie;
